### ISSUE TITLE
I want to Fix Readme file code error

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [sazamansari/node.js-_microservices#17]
I found an error in the code of the readme file, 
The `HacktoberFest` heading under **Contributions** is not aligned properly and there is an error in the code 

## ScreenShot:
![image](https://github.com/sazamansari/node.js-_microservices/assets/85278243/f0dcc4d4-86f3-43d5-831a-61829e10ba5c)

Please assign me this issue under GSSOC'23
I will be fixing the code in the `README.md` file

**Comment by sazamansari** [comment]
okk
