### ISSUE TITLE
[GSSOC'23] Add feature of Role-based access control

### ISSUE THREAD

**Issue by vivxsdb** [sazamansari/node.js-_microservices#24]
Actually I want to add support to define the  different levels of access for different users or groups of users ( i.e admin , user , guest ) to provide an additional layer of security and help ensure that sensitive data and functionality is only accessible to authorized users. This could be implemented using middleware functions in Express.js and would make the application more robust and secure.
 Can U please assign me this Issue under GSSOC'23

**Comment by sazamansari** [comment]
okk kindly start work i give you assign for you #GSSOC'23

**Comment by vivxsdb** [comment]
Please assign me this issue I want to work it

**Comment by vivxsdb** [comment]
Please assign me this issue under gssoc'23

**Comment by vivxsdb** [comment]
No it is my idea

**Comment by mridul45** [comment]
Dont worry i am not saying to assign to me only i was only asking to collaborate.

**Comment by vivxsdb** [comment]
Okk

**Comment by vivxsdb** [comment]
Then it is okay for me
