### ISSUE TITLE
adding tech stack badges and shields in readme

### ISSUE THREAD

**Issue by mridulsaggi** [sazamansari/node.js-_microservices#25]
i would like to add tech stack badges and shields in readme . it makes the readme look more pretty and give better information about the technologies used.
please assign me this issue as gssoc contribution
example:
![image](https://github.com/sazamansari/node.js-_microservices/assets/91930535/802d91fb-13e6-471d-8f93-6ef2e40a5c01)

**Comment by sazamansari** [comment]
okk adding and get me pull request
