### ISSUE TITLE
official documentation page for user-auth-microservice 

### ISSUE THREAD

**Issue by sazamansari** [sazamansari/node.js-_microservices#27]
create landing page
create read.md file
user friendly documentation page

**Comment by lovetyagi-17** [comment]
Hello @sazamansari, I can start working on this.

-  The content for readme.md file will be.
    1. What nodejs-_microservice is ?
    2. How to setup a project into a local system.
    3. How to contribute(standards)

- Guide me for landing page, what exactly we need for this page or any example for that.

Thanks

**Comment by lovetyagi-17** [comment]
I mentioned those points as point of implementation.
  If you feel , the points i mentioned correct so just assign me this.
So that I can start working on this.

**Comment by sazamansari** [comment]
yes , you can start working
