### ISSUE TITLE
add new feature

### ISSUE THREAD

**Issue by sazamansari** [sazamansari/node.js-_microservices#28]
connect with any database

user friendly login and signup page

**Comment by lovetyagi-17** [comment]
Hello @sazamansari, I can start that with MongoDB, but before that i have a few queries related to project setup and working.

**Comment by Goodluck-dc14** [comment]
Hi @sazamansari 

I am interested in working on the "connect with any database(Login and Signup page)" on the project. I am a MERN stack developer and I have experience with MongoDb database. I am available to start working immediately.
Can you please assign me this issue under #GSSoC'23?.

Thank you for your time and consideration.
