### ISSUE TITLE
Node modules issue

### ISSUE THREAD

**Issue by lovetyagi-17** [sazamansari/node.js-_microservices#29]
Hello, @sazamansari , while pushing code to the repo the node modules are also pushed, which is i believe not good, so allow me to resolve this issue.

Thanks

**Comment by lovetyagi-17** [comment]
Hello @sazamansari , please have look in to this PR, the issue is resolved.
https://github.com/sazamansari/node.js-_microservices/pull/31

**Comment by sazamansari** [comment]
0kk

**Comment by lovetyagi-17** [comment]
An PR is created and merged.
https://github.com/sazamansari/node.js-_microservices/pull/31
Thanks
