### ISSUE TITLE
[DOCS] <Add more About  NPM in information details into the about Section>

### ISSUE THREAD

**Issue by mahak-dev** [sazamansari/node.js-_microservices#33]
### Description

Hello,
Suggestion:- My suggestion is an about section more detail could be added. Please assign this task to me under GSSOC'2023.

### Screenshots

<img width="1440" alt="Screenshot 2023-05-31 at 7 17 25 PM" src="https://github.com/sazamansari/node.js-_microservices/assets/55080310/5bc8d9c1-979b-4211-8b53-66b084427a48">

**Comment by sazamansari** [comment]
@mahak-dev kindly start work send the pull request
