### ISSUE TITLE
 app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by Abhinavcode13** [sazamansari/node.js-_microservices#42]
### Description

Nodemon got crashed , it can't be deployed.

### Screenshots

![image](https://github.com/sazamansari/node.js-_microservices/assets/126642111/bf2a99ef-63b0-4695-bb47-5216132f26a6)

**Comment by sazamansari** [comment]
follow the link -  https://stackoverflow.com/questions/37486631/nodemon-app-crashed-waiting-for-file-changes-before-starting
