### ISSUE TITLE
design landing page for and add documentation for project

### ISSUE THREAD

**Issue by sazamansari** [sazamansari/node.js-_microservices#52]
### Description

design website

**Comment by Anushkabh** [comment]
I would like to take this issue . please assign it to me @sazamansari .

**Comment by MohammadBinAftab** [comment]
I would like to take this issue. Please assign me this issue. I am trying very hard. Please assign me this. @sazamansari

**Comment by sazamansari** [comment]
okk @Anushkabh  assigned you

**Comment by MohammadBinAftab** [comment]
Hey @sazamansari do you have any logo that i can put on navbar on the landing page. I need some photos to put on landing page.

**Comment by sazamansari** [comment]
@MohammadBinAftab create free logo from any where and just put on it

**Comment by Ja3mamtora** [comment]
@sazamansari Can i create a logo for you ?
