### ISSUE TITLE
Add hover to buttons on the footer

### ISSUE THREAD

**Issue by smty2018** [sazamansari/node.js-_microservices#67]
### Description

want to Add hover to buttons on the footer
![image](https://github.com/sazamansari/node.js-_microservices/assets/74114936/bff5418b-d636-492a-b72a-194916ee4168)

**Comment by Saimurugeshwari** [comment]
can i work on this

**Comment by smty2018** [comment]
@sazamansari can you please assign it to me under gssoc'23
