### ISSUE TITLE
[FEATURE]  Want to add Style on scrollbar

### ISSUE THREAD

**Issue by HimanshuNarware** [sazamansari/node.js-_microservices#68]
### Description

The scrollbar of the website is missing style, I want to add styling on  it.

### Screenshots

![103](https://github.com/sazamansari/node.js-_microservices/assets/83147410/16235c27-ee27-4683-8ee9-d153a1227271)

**Comment by sazamansari** [comment]
you can create official website for can do it now @HimanshuNarware

**Comment by Saimurugeshwari** [comment]
can i work on this under GSSOC23

**Comment by HimanshuNarware** [comment]
> you can create official website for can do it now @HimanshuNarware

@sazamansari  can i start working on this issue

**Comment by Rish-02** [comment]
@HimanshuNarware  yes you can start
