### ISSUE TITLE
[GSSOC'23] Role based access to the website 

### ISSUE THREAD

**Issue by vivxsdb** [sazamansari/node.js-_microservices#74]
### Description

Actually I want to implement this feature if the user is guest we will make him to use only some part of the website if he is authenticate user we will make him to use full website Can u please assign me this issue under GSSOC'23

**Comment by LaxmanSingh07** [comment]
hey @sazamansari  is this issue has resolved? 
if not, Please Assign me the task under GSSOC'23. I am eager to work on it.

**Comment by vivxsdb** [comment]
Hey laxman  it is my idea
